# Generated by Django 5.1.4 on 2024-12-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_is_pinned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_pinned",
        ),
    ]
